site_name: Korea Geovariable
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Database Setup: getting-started/database-setup.md
  - Usage:
    - Basic Usage: usage/basic-usage.md
    - Available Calculators: usage/calculators.md
    - Examples: usage/examples.md
  - API Reference:
    - Point Based Calculations: api/point-based-calculations.md
    - Border Based Calculations: api/border-based-calculations.md
  - Development:
    - Contributing: development/contributing.md
    - Code Style: development/code-style.md
    - Architecture: development/architecture.md
    - Database: development/database.md
    - Deployment: development/deployment.md
    - Release Process: development/release-process.md
    - Testing: development/testing.md
    - Troubleshooting: development/troubleshooting.md
