// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afiwsfknajxhendblfut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmaXdzZmtuYWp4aGVuZGJsZnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzg3NDEsImV4cCI6MjA2MjkxNDc0MX0.eIM-Nhy7yPToKdEpM0UXiH1NiQ3dioxktoNP3-DsjPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);